---
Name: controllerpolicy
---
Injector:
  RequestProcessor:
    properties:
      filters:
        - '%$ControllerPolicyRequestFilter'
ControllerPolicyApplicator:
  dependencies:
    RequestFilter: '%$ControllerPolicyRequestFilter'
Controller:
  extensions:
    - ControllerPolicyApplicator
